version: "3.8"
services:
    postgres:
        image: postgres:alpine
        environment:
         POSTGRES_DB: ${DB_NAME}
         POSTGRES_USER: ${DB_USER}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
        - "5432:5432"
        env_file: 
          - .env

    app:
        build: .
        volumes:
          - ./:/server/http
        depends_on:
        - postgres
        links:
        - postgres
        ports:
        - "8080:8080"
        env_file: 
          - .env

